title: UK Top 20 Youtubers
description: Discover the top 20 YouTubers in the UK, featuring their channels, subscriber counts, and most popular videos.

# Remote theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

# User information
user:
  name: Rethabile Molai
  profile_pic: assets/images/profile_pic.png
  linkedin_url: https://www.linkedin.com/in/rethabilemolai/

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
