title: UK Top 20 Youtubers
description: Discover the top 20 YouTubers in the UK, featuring their channels, subscriber counts, and most popular videos.
logo: assets/images/logo.png
show_downloads: true

# Remote theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Author information
author:
  name: Rethabile Molai
  avatar: assets/images/profile_pic.jpg
  bio: Researcher, content creator, and social media enthusiast.
  location: United Kingdom
  links:
    - label: GitHub
      url: https://github.com/rmolai
    - label: LinkedIn
      url: https://www.linkedin.com/in/rethabilemolai/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
